generator:
  class: sfAdminTemplateGenerator
  param:
    model_class:           Fiche
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fiche
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          credentials: [create]
        _add:
          label: Ajouter fille
          action: add
          credentials: [create]
        _unresolve:
          label: Rouvrir fiche
        _resolve:
          label: Fermer fiche
        _close:
          label: Clore
        _show:
          label: Consulter
          action: show
      fields:
        Childrens:
          label: Filles
        search:
          label: Rechercher
        created_at:
          label: Créée le
        criticity:
          label: Criticité
        label:
          label: Intitulé intervention
        tags:
          label: Tags
        is_finished:
          label: Cloturé
        is_resolved:
          label: Fermée
        parent_number:
          label: Parent
        parent:
          label: Parent
        finished_author_id:
          label: Auteur
        FinishedAuthor:
          label: Auteur
        resolved_author_id:
          label: Auteur résolution
        ResolvedAuthor:
          label: Auteur résolution
        appareil_id:
          label: Appareil
        Appareil:
          label: Appareil
        category_id:
          label: Catégorie
        Category:
          label: Catégorie
        number:
          label: Numéro
        fiche_date:
          label: Intervention
        poste_id:
          label: Poste
        Poste:
          label: Poste
        ppc_id:
          label: N° Plan Prévention Cadre
        Ppc:
          label: N° Plan Prévention Cadre
        ppi_number:
          label: N° Plan de Prévention pour l'Intervention
        mo_number:
          label: N° Mode Opératoire
        acr_number:
          label: N° Analyse Commune des Risques
        case_code_id:
          label: Code affaire
        CaseCode:
          label: Code affaire
        is_cmr:
          label: Zone CMR
        demandeur_id:
          label: Demandeur
        Demandeur:
          label: Demandeur
        appel_hour:
          label: Heure d'appel
        start_hour:
          label: Heure de début
        end_hour:
          label: Heure de fin
        batiment_id:
          label: Bâtiment
        Batiment:
          label: Bâtiment
        atelier_id:
          label: Atelier
        Atelier:
          label: Atelier
        annexe_id:
          label: Annexe
        Annexe:
          label: Annexe
        problem:
          label: Problème
        cause:
          label: Cause
        solution:
          label: Solution
        unsolved_name:
          label: Vu avec
        unsolved_date:
          label: le
        is_tested:
          label: Testé
        test_mechanic:
          label: Mécanicien
        test_operator:
          label: Opérateur
        is_stopped:
          label: Arrêt production
        is_ips:
          label: IPS
        is_controlled:
          label: Résolue
        sf_guard_user_id:
          label: Intervenant
        sfGuardUser:
          label: Intervenant
        elements_list:
          label: Eléments
        changed_elements_list:
          label: Eléments changés
        installed_elements_list:
          label: Eléments installés
      list:
        title: Fiches
        display: [number, Category, fiche_date, is_finished]
        batch_actions: []
        table_method: findActive
        object_actions:
          _edit: ~
          _show: ~
          _add: ~
          _resolve: ~
          _unresolve: ~
          _close: ~
        actions:
          _new: ~
      show:
        title: %%number%%
        actions:
          _list: ~
          _edit: ~
          _resolve: ~
          _unresolve: ~
          _close: ~
          _add: ~
        display:
          Intervenant: [sfGuardUser, Poste, label]
          Sécurité: [Ppc, ppi_number, acr_number, mo_number]
          Intervention: [_parent, fiche_date, criticity, Demandeur, appel_hour, start_hour, end_hour, _time_spent]
          Localisation: [appareil_id, tags, Batiment, Atelier, Annexe, is_cmr]
          Symptomes: [problem, cause, solution]
          Résolution: [is_tested, test_mechanic, test_operator, _is_stopped, _is_ips, is_controlled, unsolved_name, unsolved_date]
          Maintenance: [_elements]
          Filles: [_childrens]
      filter:
        display: [fiche_date, is_resolved, is_finished, search]
      form:
        actions:
          _save: ~
          _list: ~
          _show: ~
        display:
          Intervenant: [sf_guard_user_id, poste_id, label]
          Sécurité: [ppc_id, ppi_number, acr_number, mo_number]
          Intervention: [case_code_id, fiche_date, criticity, demandeur_id, appel_hour, start_hour, end_hour, _time_spent]
          Localisation: [appareil_id, tags, batiment_id, atelier_id, annexe_id, is_cmr]
          Symptomes: [problem, cause, solution]
          Résolution: [is_tested, test_mechanic, test_operator, is_stopped, is_ips, is_controlled, unsolved_name, unsolved_date]
          Maintenance: [elements_list]
      edit:
        title: Fiche n°%%number%% %%CaseCode%% %%category_code%%
      new:
        title: Nouvelle fiche