generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Fiche
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fiche
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions:
        _new:
          credential: [create]
        _edit:
          credential: [edit]
        _resolve:
          credential: [resolve]
        _close:
          credential: [close]
        _add:
          label: 'Ajouter fille'
          action: add
          credential: [create]
        _show:
          label: Consulter
          action: show
      fields:
        search:
          label: Rechercher
        label:
          label: Intitulé intervention
        tags:
          label: Tags
        is_finished:
          label: Cloturé
        is_resolved:
          label: Résolu
        parent_id:
          label: Parent
        parent:
          label: Parent
        finished_author_id:
          label: Auteur
        FinishedAuthor:
          label: Auteur
        resolved_author_id:
          label: Auteur résolution
        ResolvedAuthor:
          label: Auteur résolution
        appareil_id:
          label: Appareil
        Appareil:
          label: Appareil
        category_id:
          label: Catégorie
        Category:
          label: Catégorie
        number:
          label: Numéro
        fiche_date:
          label: Date
        poste_id:
          label: Poste
        Poste:
          label: Poste
        ppc_number:
          label: Numéro PPC
        ppi_number:
          label: Numéro PPI
        mo_number:
          label: Numéro MO
        acr_number:
          label: Numéro ACR
        case_code_id:
          label: Code affaire
        CaseCode:
          label: Code affaire
        is_cmr:
          label: Zone CMR
        demandeur_id:
          label: Demandeur
        Demandeur:
          label: Demandeur
        appel_hour:
          label: Heure d'appel
        start_hour:
          label: Heure de début
        end_hour:
          label: Heure de fin
        time_spent:
          label: Temps passé
        batiment_id:
          label: Bâtiment
        Batiment:
          label: Bâtiment
        atelier_id:
          label: Atelier
        Atelier:
          label: Atelier
        annexe_id:
          label: Annexe
        Annexe:
          label: Annexe
        problem:
          label: Problème
        cause:
          label: Cause
        solution:
          label: Solution
        unsolved_name:
          label: Vu avec
        unsolved_date:
          label: le
        is_tested:
          label: Testé
        test_mechanic:
          label: Mécanicien
        test_operator:
          label: Opérateur
        is_stopped:
          label: Arrêt production
        is_ips:
          label: IPS
        is_controlled:
          label: Controllé
        sf_guard_user_id:
          label: Intervenant
        sfGuardUser:
          label: Intervenant
        elements_list:
          label: Eléments
        changed_elements_list:
          label: Eléments changés
        installed_elements_list:
          label: Eléments installés
      list:
        title: Fiches
        display: [number, Category, fiche_date, is_finished]
        batch_actions: []
        object_actions:
          _edit: ~
          _show: ~
          _add: ~
        actions:
          _new: ~
      filter:
        display: [fiche_date, is_resolved, is_finished, search]
      form:
        actions:
          _save: ~
          _list: ~
        display:
          Intervenant: [sf_guard_user_id, poste_id, label]
          Sécurité: [ppc_number, ppi_number, acr_number, mo_number]
          Intervention: [fiche_date, demandeur_id, appel_hour, start_hour, end_hour, time_spent]
          Localisation: [tags, batiment_id, atelier_id, annexe_id, is_cmr]
          Symptomes: [problem, cause, solution]
          Résolution: [is_tested, test_mechanic, test_operator, is_stopped, is_ips, is_controlled, unsolved_name, unsolved_date]
          Maintenance: [elements_list]
      edit:
        title: Fiche n°%%number%% %%CaseCode%% %%category_code%%
      new:
        title: Nouvelle fiche
