enableKeyboard:
  is_secure: false

new:
  credentials: [create]

create:
  credentials: [create]

edit:
  credentials: [edit]

resolve:
  credentials: [resolve]

unresolve:
  credentials: [resolve]

close:
  credentials: [close]

export:
  credentials: [export]

tags_autocomplete:
  is_secure: false

demandeur_autocomplete:
  is_secure: false