enableKeyboard:
  is_secure: false

tags_autocomplete:
  is_secure: false

demandeur_autocomplete:
  is_secure: false

dashboard:
  credentials: [search]

new:
  credentials: [create]

create:
  credentials: [create]

export:
  credentials: [export]

close:
  credentials: [close]

show:
  credentials: [[view, view-resolved, show-resolved, show-closed]]

edit:
  credentials: [[edit-own, edit-resolved]]

resolve:
  credentials: [[resolve, resolve-own]]

unresolve:
  credentials: [[reopen, reopen-own]]