generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Poste
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          poste
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name:
          label: Nom
        is_active:
          label: Actif
      list:
        title: Postes
      filter:  ~
      form:    ~
      edit:
        title: Edition de "%%name%%"
      new:
        title: Nouveau poste
