generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Atelier
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          atelier
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        search:
          label: Rechercher
        name:
          label: Nom
        is_active:
          label: Actif
      show:
        title: %%name%%
        display: [name, is_active]
      list:
        title: Ateliers
        display: [name, is_active]
      filter:
        display: [search]
      form:    ~
      edit:
        title: Edition de "%%name%%"
      new:
        title: Nouvel atelier
