indexSuccess:
  stylesheets: [-*, layout.css, styles.css, /js/jqtransformplugin/jqtransform.css]
  javascripts: [-*, jquery-1.4.4.min.js, jqtransformplugin/jquery.jqtransform.js, admin.js]
  layout: admin

editSuccess:
  stylesheets: [-*, layout.css, styles.css, /js/jqtransformplugin/jqtransform.css]
  javascripts: [-*, jquery-1.4.4.min.js, jqtransformplugin/jquery.jqtransform.js, admin.js]
  layout: admin

newSuccess:
  stylesheets: [-*, layout.css, styles.css, /js/jqtransformplugin/jqtransform.css]
  javascripts: [-*, jquery-1.4.4.min.js, jqtransformplugin/jquery.jqtransform.js, admin.js]
  layout: admin