<?php

/**
 * AnnexeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnexeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnexeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Annexe');
    }
}