<?php

/**
 * AppareilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppareilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppareilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Appareil');
    }
}