<?php

/**
 * AtelierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AtelierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AtelierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Atelier');
    }
}