<?php

/**
 * CaseCodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CaseCodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CaseCodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CaseCode');
    }
}