<?php

/**
 * Demandeur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    els
 * @subpackage model
 * @author     Vincent CHALAMON <vincentchalamon@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Demandeur extends BaseDemandeur {
  public function preSave($event) {
    parent::preSave($event);
    $this->setName(strtoupper($this->getName()));
  }

}
