<?php

/**
 * Element
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    els
 * @subpackage model
 * @author     Vincent CHALAMON <vincentchalamon@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Element extends BaseElement {

  /**
   * Render element to string
   *
   * @return string Element to string
   */
  public function __toString() {
    return sprintf("%s - %s", $this->getMarque(), $this->getType());
  }
  
  public function postInsert($event) {
    parent::postInsert($event);
    if(sfContext::hasInstance() && sfContext::getInstance()->getRequest()->getParameter('action') == 'import') {
      $this->setServerId($this->getPrimaryKey())->save();
    }
  }

}
