<?php

/**
 * ElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Element');
    }
}