<?php

/**
 * Fiche
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    els
 * @subpackage model
 * @author     Vincent CHALAMON <vincentchalamon@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fiche extends BaseFiche {

  public function hasParent() {
    return $this->getParentId() != $this->getPrimaryKey() && $this->getParent();
  }

  public function resolve($return = false) {
    if(!count($this->getHierarchyIds())) {
      return;
    }
    $this->getTable()->createQuery()
            ->set('is_resolved', true)
            ->set('resolved_author_id', sfContext::getInstance()->getUser()->getGuardUser()->getPrimaryKey())
            ->whereIn('id', $this->getHierarchyIds())
            ->update()->execute();
  }

  public function close() {
    if(!count($this->getHierarchyIds())) {
      return;
    }
    $this->getTable()->createQuery()
            ->set('is_finished', true)
            ->set('finished_author_id', sfContext::getInstance()->getUser()->getGuardUser()->getPrimaryKey())
            ->whereIn('id', $this->getHierarchyIds())
            ->update()->execute();
  }

  /**
   *
   * @return array
   */
  protected function getHierarchyIds() {
    if(!sfContext::hasInstance() || !sfContext::getInstance()->getUser()->isAuthenticated()) {
      return array();
    }
    $ids = array($this->getPrimaryKey());
    if($this->hasParent()) {
      $ids = array_merge($ids, $this->getParent()->resolve(true));
    }
    if($this->getChildrens()->count()) {
      $ids = array_merge($ids, $this->getChildrens()->getPrimaryKeys());
    }
    return $ids;
  }

  public function getCategoryCode() {
    return $this->getCategory()->getCode();
  }

  public function preSave($event) {
    parent::preSave($event);
    // Force number
    if(!$this->getNumber()) {
      $number = $this->getTable()->createQuery()
              ->where('fiche_date = ?', date('Y-m-d'))
              ->count();
      $this->setNumber(preg_replace('/\-/i', '', $this->getFicheDate()).sfConfig::get('app_machine_id').str_pad($number+1, 4, "0", STR_PAD_LEFT));
    }
    // Force time spent
    if(!$this->getTimeSpent()) {
      $this->setTimeSpent(date('H:i:s', strtotime($this->getEndHour() - $this->getStartHour())));
    }
  }

}