<?php

/**
 * FicheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicheTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fiche');
    }
}