<?php

/**
 * FicheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object FicheTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Fiche');
  }

  public function findActive(Doctrine_Query $query = null, $action = null) {
    if(is_null($query)) {
      $query = $this->createQuery('q');
    }
    $query->andWhere($query->getRootAlias().'.deleted_at IS NULL')
            ->addOrderBy($query->getRootAlias().'.number ASC');
    return $action ? $query->$action() : $query;
  }

}