<?php

/**
 * FicheLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    els
 * @subpackage model
 * @author     Vincent CHALAMON <vincentchalamon@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FicheLog extends BaseFicheLog
{
  
  protected $logs;
  public function getLogs() {
    if(is_null($this->logs)) {
      $this->logs = $this->getNumber() ? $this->getTable()->findByParentNumber($this->getNumber()) : new Doctrine_Collection(get_class($this));
    }
    return $this->logs;
  }
  
  protected $parent;
  public function getParent() {
    if(is_null($this->parent)) {
      $this->parent = false;
      if($this->getParentNumber() && $this->getNumber() && $this->getParentNumber() != $this->getNumber()) {
        $this->parent = $this->getTable()->findOneByNumber($this->getParentNumber());
      }
    }
    return $this->parent;
  }
  
}
