<?php

/**
 * FicheSfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheSfGuardUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicheSfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FicheSfGuardUser');
    }
}