<?php

/**
 * FicheElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicheElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FicheElement');
    }
}