<?php

/**
 * Fiche
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    els
 * @subpackage model
 * @author     Vincent CHALAMON <vincentchalamon@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fiche extends BaseFiche {

  /**
   * Render fiche to string
   *
   * @return string Label
   */
  public function __toString() {
    return sprintf("Fiche n°%s %s %s", $this->getNumber(), $this->getCaseCode(), $this->getCategoryCode());
  }

  /**
   * Check if current fiche has parent
   *
   * @return boolean Condition
   */
  public function hasParent() {
    return $this->getParentId() != $this->getPrimaryKey() && $this->getParent();
  }

  /**
   * Resolve current fiche, parent and children
   *
   * @param boolean $return Return list of ids to resolve hierarchy
   * @return mixed Void or list of ids
   */
  public function resolve($return = false) {
    if(!count($this->getHierarchyIds())) {
      return;
    }
    if($return) {
      return $this->getHierarchyIds();
    }
    $this->getTable()->createQuery()
            ->set('is_resolved', true)
            ->set('resolved_author_id', sfContext::getInstance()->getUser()->getGuardUser()->getPrimaryKey())
            ->whereIn('id', $this->getHierarchyIds())
            ->update()->execute();
  }

  /**
   * Close current fiche
   *
   * @return void
   */
  public function close() {
    if(!count($this->getHierarchyIds())) {
      return;
    }
    $this->getTable()->createQuery()
            ->set('is_finished', true)
            ->set('finished_author_id', sfContext::getInstance()->getUser()->getGuardUser()->getPrimaryKey())
            ->whereIn('id', $this->getHierarchyIds())
            ->update()->execute();
  }

  /**
   *
   * @return array Ids
   */
  protected function getHierarchyIds() {
    if(!sfContext::hasInstance() || !sfContext::getInstance()->getUser()->isAuthenticated()) {
      return array();
    }
    $ids = array($this->getPrimaryKey());
    if($this->hasParent()) {
      $ids = array_merge($ids, $this->getParent()->resolve(true));
    }
    if($this->getChildrens()->count()) {
      $ids = array_merge($ids, $this->getChildrens()->getPrimaryKeys());
    }
    return $ids;
  }

  /**
   * Get category code
   *
   * @return string
   */
  public function getCategoryCode() {
    return $this->getCategory()->getCode();
  }

  /**
   * Force fiche number and time spent
   * 
   * @param Doctrine_Event $event Event
   */
  public function preSave($event) {
    parent::preSave($event);
    // Force number
    if(!$this->getNumber()) {
      $number = $this->getTable()->createQuery()
                      ->where('fiche_date = ?', date('Y-m-d'))
                      ->count();
      $this->setNumber(preg_replace('/\-/i', '', date('Y-m-d')).sfConfig::get('app_machine_id').str_pad($number + 1, 4, "0", STR_PAD_LEFT));
    }
  }

}