<?php

/**
 * FicheLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicheLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FicheLog');
    }
}