<?php

/**
 * PosteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PosteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PosteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Poste');
    }
}