all:
  sf_guard_plugin:
    success_signin_url: "@homepage"
  machine_id: A
  sf_admin_template:
    menus:
      fiche:
        label: Fiches
      appareil:
        label: Appareils
        credentials: [fixtures]
      atelier:
        label: Ateliers
        credentials: [fixtures]
      batiment:
        label: Bâtiments
        credentials: [fixtures]
      annexe:
        label: Annexes
        credentials: [fixtures]
      case_code:
        label: Codes affaire
        credentials: [fixtures]
      ppc:
        label: Numéros PPC
        credentials: [fixtures]
      category:
        label: Catégories
        credentials: [fixtures]
      demandeur:
        label: Demandeurs
        credentials: [fixtures]
      element:
        label: Eléments
        credentials: [fixtures]
      poste:
        label: Postes
        credentials: [fixtures]
      sf_guard_user:
        label: Utilisateurs
      sf_guard_group:
        label: Groupes d'utilisateurs
        credentials: [admin]
      sf_guard_permission:
        label: Permissions d'utilisateurs
        credentials: [admin]