all:
  sf_guard_plugin:
    success_signin_url: "@homepage"
  machine_id: A
  sf_admin_template:
    menus:
      fiche:
        label: Fiches
      search:
        label: Rechercher
        credentials: [search]
      export:
        label: Exporter
        credentials: [export]
      document:
        label: Documents
        credentials: [[create-document, document]]
      appareil:
        label: Appareils
        credentials: [appareil]
      element:
        label: Eléments
        credentials: [element]
      atelier:
        label: Ateliers
        credentials: [fixtures]
      batiment:
        label: Bâtiments
        credentials: [fixtures]
      annexe:
        label: Annexes
        credentials: [fixtures]
      case_code:
        label: Codes
        credentials: [fixtures]
      ppc:
        label: PPC
        credentials: [fixtures]
      category:
        label: Catégories
        credentials: [fixtures]
      demandeur:
        label: Demandeurs
        credentials: [fixtures]
      poste:
        label: Postes
        credentials: [fixtures]
      sf_guard_user:
        label: Utilisateurs
      sf_guard_group:
        label: Groupes
        credentials: [admin]