# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    login_module:           sfGuardAuth
    login_action:           signin
    secure_module:          sfGuardAuth
    secure_action:          secure
    error_404_module:       front
    error_404_action:       error404
  .settings:
    csrf_secret:            42e51e41a347e15e8f7cfc59ea62262c0aef171b
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    use_database:           true
    enabled_modules:        [default, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission]
    i18n:                   true
    default_culture:        fr
    standard_helpers:       [Partial, Cache, Asset, I18N, Tools, Date, Tags]