# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ELS - Criels
    description:  ELS - Criels
    keywords:     ELS - Criels
    language:     fr
    robots:       index, follow

  stylesheets:    [/sfEPFactoryFormPlugin/switcher/js-switcher.css, main.css]

  javascripts:    [/sfEPFactoryFormPlugin/switcher/switcher.js]

  has_layout:     true
  layout:         admin
