generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Category
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        search:
          label: Rechercher
        name:
          label: Nom
        code:
          label: Code
        is_active:
          label: Actif
      show:
        title: %%name%%
        display: [name, code, is_active]
      list:
        title: Catégories
        display: [name, code, is_active]
        table_method: findActive
      filter:
        display: [search]
      form:    ~
      edit:
        title: Edition de "%%name%% %%code%%"
      new:
        title: Nouvelle catégorie
