<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('fiche', 'parent_number', 'string', '13', array());
        $this->addColumn('fiche_log', 'parent_number', 'string', '13', array());
    }

    public function down()
    {
        $this->removeColumn('fiche', 'parent_number');
        $this->removeColumn('fiche_log', 'parent_number');
    }
}