<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('fiche', 'fiche_parent_id_fiche_id');
        $this->dropForeignKey('fiche_log', 'fiche_log_parent_id_fiche_id');
        $this->addIndex('fiche', 'fiche_parent_number', array(
             'fields' => 
             array(
              0 => 'parent_number',
             ),
             ));
        $this->addIndex('fiche', 'number', array(
             'fields' => 
             array(
              0 => 'number',
             ),
             ));
        $this->addIndex('fiche_log', 'fiche_log_parent_number', array(
             'fields' => 
             array(
              0 => 'parent_number',
             ),
             ));
        $this->createForeignKey('fiche', 'fiche_parent_number_fiche_number', array(
             'name' => 'fiche_parent_number_fiche_number',
             'local' => 'parent_number',
             'foreign' => 'number',
             'foreignTable' => 'fiche',
             ));
        $this->createForeignKey('fiche_log', 'fiche_log_parent_number_fiche_number', array(
             'name' => 'fiche_log_parent_number_fiche_number',
             'local' => 'parent_number',
             'foreign' => 'number',
             'foreignTable' => 'fiche',
             ));
    }

    public function down()
    {
        $this->createForeignKey('fiche', 'fiche_parent_id_fiche_id', array(
             'name' => 'fiche_parent_id_fiche_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'fiche',
             ));
        $this->createForeignKey('fiche_log', 'fiche_log_parent_id_fiche_id', array(
             'name' => 'fiche_log_parent_id_fiche_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'fiche',
             ));
        $this->dropForeignKey('fiche', 'fiche_parent_number_fiche_number');
        $this->dropForeignKey('fiche_log', 'fiche_log_parent_number_fiche_number');
        $this->removeIndex('fiche', 'fiche_parent_number', array(
             'fields' => 
             array(
              0 => 'parent_number',
             ),
             ));
        $this->removeIndex('fiche', 'number', array(
             'fields' => 
             array(
              0 => 'number',
             ),
             ));
        $this->removeIndex('fiche_log', 'fiche_log_parent_number', array(
             'fields' => 
             array(
              0 => 'parent_number',
             ),
             ));
    }
}