Poste:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Category:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    code: integer(3)
    is_active:
      type: boolean
      default: true

CaseCode:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Ppc:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Appareil:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Demandeur:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Batiment:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    sigle:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Element:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    marque:
      type: string(255)
      notnull: true
    type:
      type: string(255)
      notnull: true
    ref:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Atelier:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Annexe:
  actAs:
    Timestampable: ~
    SoftDelete: ~
  columns:
    name:
      type: string(255)
      notnull: true
    is_active:
      type: boolean
      default: true

Fiche:
  actAs:
    Timestampable: ~
    SoftDelete: ~
    Taggable: ~
  columns:
    criticity:
      type: integer
      default: 0
    sf_guard_user_id: integer
    parent_id: integer
    is_finished:
      type: boolean
      default: false
    finished_author_id: integer
    is_resolved:
      type: boolean
      default: false
    resolved_date: timestamp
    resolved_author_id: integer
    category_id:
      type: integer
      notnull: true
    case_code_id:
      type: integer
      notnull: true
    ppc_id: integer
    number:
      type: string(13)
      notnull: true
    label: string(255)
    fiche_date: date
    poste_id:
      type: integer
      notnull: true
    ppi_number:
      type: string(255)
      notnull: true
    mo_number:
      type: string(255)
      notnull: true
    acr_number:
      type: string(255)
      notnull: true
    appareil_id: integer
    is_cmr:
      type: boolean
      default: false
    demandeur_id: integer
    appel_hour: timestamp
    start_hour: timestamp
    end_hour: timestamp
    problem: clob
    cause: clob
    solution: clob
    unsolved_name: string(255)
    unsolved_date: date
    is_tested:
      type: boolean
      default: false
    test_mechanic: string(255)
    test_operator: string(255)
    is_stopped:
      type: boolean
      default: false
    is_ips:
      type: boolean
      default: false
    is_controlled:
      type: boolean
      default: false
    batiment_id:
      type: integer
      notnull: true
    atelier_id: integer
    annexe_id: integer
  relations:
    Parent:
      class: Fiche
      local: parent_id
      foreign: id
      foreignAlias: Childrens
    FinishedAuthor:
      class: sfGuardUser
      local: finished_author_id
      foreign: id
      foreignAlias: Fiches
    ResolvedAuthor:
      class: sfGuardUser
      local: resolved_author_id
      foreign: id
      foreignAlias: Fiches
    Appareil:
      foreignAlias: Fiches
    Category:
      foreignAlias: Fiches
    Poste:
      foreignAlias: Fiches
    CaseCode:
      foreignAlias: Fiches
    Ppc:
      foreignAlias: Fiches
    Demandeur:
      foreignAlias: Fiches
    Batiment:
      foreignAlias: Fiches
    Atelier:
      foreignAlias: Fiches
    Annexe:
      foreignAlias: Fiches
    sfGuardUser:
      foreignAlias: Fiches

FicheElement:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    fiche_id:
      type: integer
      notnull: true
    element_changed_id: integer
    element_changed_serial: string(255)
    element_installed_id: integer
    element_installed_serial: string(255)
  relations:
    ElementChanged:
      class: Element
      local: element_changed_id
      onDelete: SET NULL
    ElementInstalled:
      class: Element
      local: element_installed_id
      onDelete: SET NULL
    Fiche:
      onDelete: CASCADE
      foreignAlias: Elements