generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Element
    theme:                 admin_template
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          element
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        search:
          label: Rechercher
        marque:
          label: Marque
        type:
          label: Type
        ref:
          label: Référence
        is_active:
          label: Actif
      show:
        title: %%type%% %%marque%% %%ref%%
        display: [marque, type, ref, is_active]
      list:
        title: Eléments
        display: [marque, type, ref, is_active]
      filter:
        display: [search]
      form:    ~
      edit:
        title: Edition de "%%type%% %%marque%% %%ref%%"
      new:
        title: Nouvel élément
