generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Element
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          element
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        marque:
          label: Marque
        type:
          label: Type
        ref:
          label: Référence
        serial:
          label: N° de série
        is_active:
          label: Actif
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
